[build-system]
requires = ["uv_build>=0.12.4,<0.13"]
build-backend = "uv_build"

[project]
name = "edwh-auth-rbac"
version = "2.0.2"
description = 'Recursive Memberships and Permissions for the Education Warehouse Authentication System'
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = ['edwh', 'omgeving', 'whitelabel']
authors = [
    { name = "Remco Boerma", email = "remco.b@educationwarehouse.nl" },
    { name = "Robin van der Noord", email = "robin.vdn@educationwarehouse.nl" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    'edwh-migrate',
    'pydal',
    "python-dateutil",
]

[project.optional-dependencies]
dev = [
    'dotmap',
    "edwh",
    "edwh-migrate",
    "su6[all]",
    "testcontainers",
    "requests<2.32", # 2.32 breaks testcontainers
    "psycopg2-binary",
]

[project.urls]
Documentation = "https://github.com/educationwarehouse/edwh-auth-rbac#readme"
Issues = "https://github.com/educationwarehouse/edwh-auth-rbac/issues"
Source = "https://github.com/educationwarehouse/edwh-auth-rbac"


[tool.vommit]
allow_breaking_bang = true
allow_breaking_footer = true
prerelease_token = "beta"
confirm = true
ignore = []

[tool.vommit.git]
enabled = true
origin = "origin"
branch = "master"
on_wrong_branch = "error"
tag_format = "v{version}"
commit_format = "{version}"

[tool.vommit.changelog]
enabled = true
file = "CHANGELOG.md"
include_prereleases = false
placeholder = "<!--next-version-placeholder-->"
placeholder_regex = "<auto>"
entry_title_format = "## v{version} ({date:%Y-%m-%d})"

[tool.vommit.changelog.levels]
feat = "Feature{s}"
fix = "Fix{es}"
break = "Breaking Change{s}"
docs = "Documentation"
perf = "Performance"

[tool.vommit.pypi]
enabled = false
use_keyring = true

[tool.vommit.commands]
clean = "rm -rf ./dist"
build = "uv build"
publish = "uv publish"
post_publish = ""

[tool.vommit.version_bump_map]
break = "major"
feat = "minor"
fix = "patch"
perf = "patch"

[tool.su6]
directory = "src"
include = []
exclude = []
# 'all':
stop-after-first-failure = false
# pytest:
coverage = 100
badge = true
# --format json indent
json-indent = 4

[tool.black]
target-version = ["py311"]
line-length = 120
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^.*\.bak\/.+     # ignore every .bak directory
  ^.*venv.+\/.+    # ignore every venv directory
  venv.+|.+\.bak   # idk why it suddenly works, let's not touch it
)
'''

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.isort]
profile = "black"
extend_skip_glob = ["venv*"]

[tool.pytest.ini_options]
pythonpath = [
    "src",
]
